[
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "idPropriedade",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "address",
				"name": "proprietario",
				"type": "address"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "areaDesmatada",
				"type": "uint256"
			}
		],
		"name": "DesmatamentoDetectado",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "idMulta",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "idPropriedade",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "address",
				"name": "proprietario",
				"type": "address"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "valorMulta",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "timestamp",
				"type": "uint256"
			}
		],
		"name": "MultaAplicada",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "idMulta",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "address",
				"name": "pagador",
				"type": "address"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "valor",
				"type": "uint256"
			}
		],
		"name": "MultaPaga",
		"type": "event"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "idPropriedade",
				"type": "uint256"
			},
			{
				"internalType": "uint256",
				"name": "areaDesmatadaDetectada",
				"type": "uint256"
			}
		],
		"name": "detectarDesmatamento",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "idPropriedade",
				"type": "uint256"
			}
		],
		"name": "getMultasPorPropriedade",
		"outputs": [
			{
				"internalType": "uint256[]",
				"name": "",
				"type": "uint256[]"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "multaBasePorHectare",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"name": "multas",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "idPropriedade",
				"type": "uint256"
			},
			{
				"internalType": "address",
				"name": "proprietario",
				"type": "address"
			},
			{
				"internalType": "uint256",
				"name": "areaDesmatada",
				"type": "uint256"
			},
			{
				"internalType": "uint256",
				"name": "valorMulta",
				"type": "uint256"
			},
			{
				"internalType": "uint256",
				"name": "timestamp",
				"type": "uint256"
			},
			{
				"internalType": "bool",
				"name": "paga",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "_proprietario",
				"type": "address"
			}
		],
		"name": "multasEmAberto",
		"outputs": [
			{
				"internalType": "uint256[]",
				"name": "",
				"type": "uint256[]"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			},
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"name": "multasPorPropriedade",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "owner",
		"outputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "idMulta",
				"type": "uint256"
			}
		],
		"name": "pagarMulta",
		"outputs": [],
		"stateMutability": "payable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "_addr",
				"type": "address"
			}
		],
		"name": "setCartorio",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "totalMultas",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	}
]